### ISSUE TITLE
Mesa3D - NVIDIA CG fp40 vp40

### ISSUE THREAD

**Issue by Rayduxz** [pal1000/mesa-dist-win#1]
Not an issue related to your installer, works fine, but I was wondering if you could take a look at this, not sure on how to contact you besides here.

https://www.opengl.org/discussion_boards/showthread.php/199760-Mesa3D-NVIDIA-CG-and-OpenGL-profiles-vp40-fp40

Cheers!

**Comment by pal1000** [comment]
NVIDIA CG Toolkit has been discontinued since 2013, but you can give Mesa3D a shot anyway. It can render oldies that GPU drivers screw up sometimes, though I don't know how far it can go.  There are 2 off-scrreen renderers (gallium-based and swrast), and the standard desktop OpenGL (llvmpipe) to try, 
If it doesn't work you could post on mesa-dev and mesa-users mailing lists.

**Comment by Rayduxz** [comment]
Thanks for answering!

The app it's a Windows 32 bits borderless full-screen game from 2006, I'm on Windows 10 and I tried llvmpipe, gallium-based and swrast, all of them ends up in just a green screen and gives an inifinite ammount of `Mesa: User error: GL_INVALID_OPERATION in glBegin(fragment program not valid)` errors.

Since the game was compiled with NVIDIA CG OpenGL profiles vp40 fp40 it only works on NVIDIA cards. My objective is to run the game on Intel/AMD with Mesa3D but no luck so far, if you got any other ideas please let me know, maybe changing som Mesa3D parameters?

I'll try to hit the mesa mailing lists, thank you!

**Comment by adolfintel** [comment]
What game is it? Maybe I can fix it

**Comment by Rayduxz** [comment]
Hello @adolfintel!

Your Mesa3D build gives the following errors non-stop making an infinite growing log file:

```
Mesa: 1 similar GL_INVALID_OPERATION errors
Mesa: User error: GL_INVALID_OPERATION in glProgramString(bad program)
Mesa: User error: GL_INVALID_OPERATION in glProgramStringARB(invalid ARB fragment program option)

Mesa: 1 similar GL_INVALID_OPERATION errors
Mesa: User error: GL_INVALID_OPERATION in glProgramString(bad program)
Mesa: User error: GL_INVALID_OPERATION in glProgramStringARB(syntax error, unexpected $undefined, expecting ARBvp_10 or ARBfp_10)

Mesa: User error: GL_INVALID_OPERATION in glBegin(vertex program not valid)
Mesa: User error: GL_INVALID_OPERATION in glEnd
```

And regarding "What game is it?" Due to some concerns I would not like to put the game name in here. Got a direct way to contact you? Thanks!

**Comment by adolfintel** [comment]
Write me at dosse91@paranoici.org
