### ISSUE TITLE
Square particles in Quake 2

### ISSUE THREAD

**Issue by Matthaiks** [pal1000/mesa-dist-win#101]
I've tried different environment variables but particles stay square.

Mesa3D 22.0.3
Windows 10
Radeon Vega 8

Mesa3D (Zink & GLonD3D12)
![Mesa](https://user-images.githubusercontent.com/3577122/167007732-32fa0f6a-eb13-44ab-90ab-87fc0f1df99f.png)

AMD's OpenGL driver
![Native](https://user-images.githubusercontent.com/3577122/167007747-8364055f-c358-415d-a6d8-41ec99655537.png)

**Comment by pal1000** [comment]
Report [upstream](https://gitlab.freedesktop.org/mesa/mesa/-/issues).
