### ISSUE TITLE
stop distributing radv

### ISSUE THREAD

**Issue by zmike** [pal1000/mesa-dist-win#103]
RADV does not work on Windows. This is not a bug or a missing feature, it just isn't going to work. Distributing it in this package implies that it will, and this wastes the time of anyone who tries to use it.

**Comment by pal1000** [comment]
@zmike you should be aware that [if LLVM is built with AMDGPU target, Microsoft CLC fails to build if RADV isn't built as well](https://gitlab.freedesktop.org/mesa/mesa/-/issues/5666).

Anyway I took your suggestion for [22.1.0](https://github.com/pal1000/mesa-dist-win/releases/tag/22.1.0).

**Comment by zmike** [comment]
Great, thanks!

> @zmike you should be aware that [if LLVM is built with AMDGPU target, Microsoft CLC fails to build if RADV isn't built as well](https://gitlab.freedesktop.org/mesa/mesa/-/issues/5666).
> 

I don't think this is a RADV issue though? At a minimum, if you have to build RADV to work around this for now, you could just not distribute RADV after.

**Comment by pal1000** [comment]
> I don't think this is a RADV issue though?

It's not. It's a Microsoft CLC / clover issue. It was [worked around](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/13720) for clover only when using LLVM config tool.  Reading meson.build I can tell the work around doesn't apply for
Microsoft CLC though.

**Comment by zmike** [comment]
Maybe file another bug? Or update that one. Dunno, but it sounds like it should be fixed.

**Comment by oscarbg** [comment]
don't asking for enabling RADV again but note I found some usage for RADV for Windows in :
https://github.com/tgjones/shader-playground/issues/102
"It might be nice to experiment with, and it already compiles as a Vulkan ICD on Windows. It just needs RADV_FORCE_FAMILY to be set, and NIR/ACO output is available as text via VK_KHR_pipeline_executable_properties."

**Comment by Weather-OS** [comment]
Reopen this issue.
https://www.phoronix.com/news/Experimental-RADV-Windows

**Comment by kleinergoo** [comment]
I vibecoded Faith Ekstrand's [fork](https://gitlab.freedesktop.org/lfrb/mesa/-/tree/wddm2?ref_type=heads) to get it working on my RX 580. It actually works with some applications.

Works:

vkcube
BeamNG
CS2
Furmark
CSS with DXVK (D3D9)

Doesn't work properly:

All D3D11 games with DXVK (some issue with DXGI, altough some games did startup for a second until the desktop froze)
Doom: The Dark Ages with emulated RT (starts up, but crashes before reaching the main menu)

You may encounter frequent hard freezes of the entire desktop until Windows restarts the graphics driver itself.

Note: I have no programming knowledge at all, so you might have more success if you vibecode on it yourself.
