### ISSUE TITLE
Trying to use binaries on Window Server 2016, nothing happens, binaries not started

### ISSUE THREAD

**Issue by AntonOvsyannikov** [pal1000/mesa-dist-win#11]
When trying to start with Far manager it reports "Can not execute ..., The operation was cancelled by the user. Any ideas for trblshoot?

**Comment by AntonOvsyannikov** [comment]
Oh! Just renamed to .7z and unzip it, works fine!

Dear Friend, let me shake your hand! My task was to quickly enable OpenGL on the server, so without your distribution it would take a week! Thanks a lot! I was never able to put all those things together.

**Comment by pal1000** [comment]
I am using 7zip in ultra compression to make the SFX archive. I have no idea why Far Manager didn't want to run it. Some security policy at your end as it's not digitally signed, maybe.

**Comment by AntonOvsyannikov** [comment]
yes, it was security issue, thank a lot again for binaries

чт, 16 авг. 2018 г. в 16:32, pal1000 <notifications@github.com>:
