### ISSUE TITLE
Insta Crash

### ISSUE THREAD

**Issue by Directox01** [pal1000/mesa-dist-win#118]
Does it work for you guys? because I don't see anyone open an issue related to it since 22.2.0.

Whatever I'm trying to open that requires OpenGL the app crashes even OpenGL viewer

I'm running Amd Ryzen9 5950X CPU
No GPU

**Comment by Directox01** [comment]
upstream issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/7494

**Comment by Directox01** [comment]
Hello @pal1000 !

I'd like to ask may by an chance you can release an small update with the new update of ``[Improve MSVC debug info package layout]``? 

Thank you in advance.

**Comment by Directox01** [comment]
Ok, thank you. 

Do you think maybe they release 22.2.2 this week? if yes maybe worth to wait for it. However I had the issue with windows server 2019 & 2022 I forgot to mention it.

**Comment by Directox01** [comment]
Oh, ok thank you so much

**Comment by pal1000** [comment]
22.2.2 is out right on time. I already did MiinGW debug build.  MiinGW release build and MSVC build would fallow shortly.

**Comment by pal1000** [comment]
MinGW is a bit faster while MSVC is a bit more reliable. Not long ago [I reported upstream a MinGW only crash happening only with build optimized for speed](https://gitlab.freedesktop.org/mesa/mesa/-/issues/7244).

**Comment by Directox01** [comment]
That makes sense thank you!
