### ISSUE TITLE
Uninstall in VirtualBox guest?

### ISSUE THREAD

**Issue by cesss** [pal1000/mesa-dist-win#13]
Hi!

Just a quick question: I'm reading that when you install these drivers, you cannot enable again the 3D acceleration from VirtualBox. That's fine for me (in fact I'm going to use mesa-dist-win because the 3D acceleration in VirtualBox is not good enough for the apps I use), but, in case I need to enable 3D acceleration again in the future, how should I proceed? Can I uninstall mesa-dist-win, enable 3D acceleration, and later reinstall mesa-dist-win again if I wish to use Mesa again?

Thanks!

**Comment by pal1000** [comment]
Yes, if you uninstall mesa-dist-win you can re-enable 3D acceleration in VM settings afterwards. Basically you only have to avoid having all these 3 at the same time:
- guest additions installed;
- 3D acceleration enabled;
- Mesa3D desktop OpenGL driver installed system-wide in VM.

If any of these 3 triggering factors is removed from the environment you'll have no problem with Direct3D in VM.
