### ISSUE TITLE
Can RADV vulkan driver run on Windows? 

### ISSUE THREAD

**Issue by zouwen4321** [pal1000/mesa-dist-win#138]
I compile radv_vulkan.dll success, but can not find suitable device when run vulkan benchmark. My PC has AMD 6800 GPU.

**Comment by pal1000** [comment]
Unfortunately no. Only ACO compiler works in off-screen rendering mode and that's all. That''s why I dropped it from release package at the suggestion of @zmike in #103.

**Comment by zouwen4321** [comment]
Thank you.

**Comment by kleinergoo** [comment]
Yes
