### ISSUE TITLE
What is d3d10sw and how to use it?

### ISSUE THREAD

**Issue by VgaCich** [pal1000/mesa-dist-win#141]
I can't understand it from documentation...

**Comment by pal1000** [comment]
d3d10sw is a D3D10 software renderer similar to [Windows built-in WARP](https://learn.microsoft.com/en-us/windows/win32/direct3darticles/directx-warp). It was developed by VMWare. Honestly it's not very interesting especially with [Microsoft making WARP updates available independent of Windows](https://www.nuget.org/packages/Microsoft.Direct3D.WARP#versions-tab).
