### ISSUE TITLE
Mesa 23.2rc1 builds?

### ISSUE THREAD

**Issue by oscarbg** [pal1000/mesa-dist-win#152]
Hi,
A bit too early..
But supposedly still coming next week..
No pressure and hoping no new build issues..
So asking as always for Zink,dozen,vaon12, etc..
Av1 encode needs latest agility sdk headers.. but can live without testing it..

thanks..

**Comment by oscarbg** [comment]
also forgot to say.. it's rusticl on Win buildable (llvmpipe only) finally in 23.2?

**Comment by pal1000** [comment]
No as far as I know.

**Comment by pal1000** [comment]
> and hoping no new build issues

Unfortunately we are not so [lucky](https://gitlab.freedesktop.org/mesa/mesa/-/issues/9359).

**Comment by pal1000** [comment]
23,2.0-rc1 is out.
