### ISSUE TITLE
D3D12 driver: colours are messed up

### ISSUE THREAD

**Issue by jgcodes2020** [pal1000/mesa-dist-win#154]
# Summary
The D3D driver produces incorrect colours with Mupen64Plus.
# Screenshots
<p align="center">
<img src="https://github.com/pal1000/mesa-dist-win/assets/35639051/ec033f7c-3661-4af0-a36a-57539ea446ed"><br>
D3D driver (incorrect)
</p>
<p align="center">
<img src="https://github.com/pal1000/mesa-dist-win/assets/35639051/19e9ff5e-9d3b-48e2-b3d7-68ca637812b7"><br>
llvmpipe driver (correct)
</p>

**Comment by pal1000** [comment]
Rendering glitches should be reported [upstream](https://gitlab.freedesktop.org/mesa/mesa/-/issues).

**Comment by jgcodes2020** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/9460

This exists now, should I leave this issue open until that one closes?
