### ISSUE TITLE
Issues with multiple shader attachments

### ISSUE THREAD

**Issue by Arcnor** [pal1000/mesa-dist-win#170]
Hello, not sure if this should be reported here or upstream, but starting here as this is the package I'm using (thanks btw!)

I've tested a project locally that seem to have issues when the shaders use MTR (i.e. more than one attachment is linked in the shader), but only if the shader is written like:
```
out vec4 color;
out vec4 normal;
```
In this case, and for some reason, the Mesa driver inverts the outputs (I tried different backends and it happens with all of them IIRC), so the shader writes the normals to the color attachment, and vice versa.

If I change the shader to look like:
```
layout(location = 0, index = 0) out vec4 color;
layout(location = 1, index = 0) out vec4 normal;
```
the problem goes away, so it seems Mesa is assigning the wrong location to the attachments for some reason.

I unfortunately cannot share the project, but hopefully this is enough for a resolution.

**Comment by pal1000** [comment]
Please go upstream with this.

**Comment by Arcnor** [comment]
Done at https://gitlab.freedesktop.org/mesa/mesa/-/issues/10637

**Comment by pal1000** [comment]
Try 24.0.5.
