### ISSUE TITLE
Shader debug info dump

### ISSUE THREAD

**Issue by Arcnor** [pal1000/mesa-dist-win#181]
Hi,

Is there any way to dump shader PDBs (when using a D3D12 backend) or similar (when using a Vulkan backend) somewhere to disk? I've tried with `MESA_SHADER_CACHE_DIR`/`MESA_SHADER_DUMP_PATH`/`MESA_SHADER_CAPTURE_PATH` but none of those dump any conversion info, only the original GLSL.

**Comment by pal1000** [comment]
Ask [upstream](https://gitlab.freedesktop.org/mesa/mesa/-/issues) for help.
