### ISSUE TITLE
Unable to run FSO Open with the D3DGLon12

### ISSUE THREAD

**Issue by GamingCity** [pal1000/mesa-dist-win#188]
Not sure if it is a Mesa bug or it is caused because of the windows port but running FSO on Vulkan with Zink does work ok (at least with radeon hardware, tested polaris and RDNA gpus), but running it on D3D12 just gives a white screen and crashes right after.

On the game debug output i get this:

OpenGL Debug: Source:OpenGL	Type:Error	ID:2	Severity:High	Message:GL_OUT_OF_MEMORY in glBufferStorage
OpenGL Debug: Source:OpenGL	Type:Error	ID:2	Severity:High	Message:GL_INVALID_VALUE in glMapBufferRange(offset 0 + length 2134272 > buffer_size 0)

Also happens on Nvidia (RTX3060)

**Comment by pal1000** [comment]
Collect a MSVC build call stack and report [upstream](https://gitlab.freedesktop.org/mesa/mesa/-/issues).

**Comment by GamingCity** [comment]
very well

**Comment by pal1000** [comment]
The debug log indicates an out of ,memory caused by both Mesa D3D12 and NVIDIA drivers memory management issues
