### ISSUE TITLE
zlib and libstd dependencies for mingw build?

### ISSUE THREAD

**Issue by aciereszko** [pal1000/mesa-dist-win#189]
I was wondering, when I try to run my program with opengl32.dll and libgallium_wgl.dll I get a runtime error about missing zlib1.dll and libstd.dll

I am trying to upgrade from a pre 21 release, where this problem was not happening.

Is the intent that the users supply their own?

**Comment by aciereszko** [comment]
MSVC build is fine

**Comment by aciereszko** [comment]
On it!

**Comment by aciereszko** [comment]
Looks like 23.1.2 mingw and everything before is fine, and 23.1.3 and all newer versions on my machine complain about missing libstd.dll and zlib1.dll

**Comment by pal1000** [comment]
I assumed 24bcb1f96d38d95a2b90ff1637c373e9a17d0bc3 was the culprit but that's not the case.
The problem is either with Mesa or MSYS2 because [mesa-dist-win only has build environment updates in between](https://github.com/pal1000/mesa-dist-win/compare/23.1.2...23.1.3).

**Comment by pal1000** [comment]
Also your issue report is duplicate of #156.

**Comment by aciereszko** [comment]
I see thanks.

Any reason why one would prefer binaries compiles with MSVC vs MinGW?

**Comment by pal1000** [comment]
MSVC binaries are more stable while MinGW were a bit faster when they were working but could crash when MSVC binaries are not.

**Comment by aciereszko** [comment]
Ok, thanks
