### ISSUE TITLE
Add file infos to dlls

### ISSUE THREAD

**Issue by movedoa** [pal1000/mesa-dist-win#19]
Currently the fileinfos are empty.
It would be nice to have at lest the mesa version somewhere in the fileinfos so i can identify what version of mesa i am currently using.

![grafik](https://user-images.githubusercontent.com/13309951/51251407-8f841700-1999-11e9-9d52-ea9c06b9d56a.png)

**Comment by pal1000** [comment]
I looked into this. It can be done in Visual Studio post compilation. I'd like to be able to automate it somehow though without relying on 3rd party software. Suggestion is appreciated.

**Comment by pal1000** [comment]
Posted Mesa3D 18.3.2 binaries with this feature request addressed, I'll keep this open until I automate the resource injection process. For this release I did it entirely by hand in Visual Studio for all 10 DLLs, a typo prone and time consuming process.

**Comment by wangwenx190** [comment]
@pal1000 Great job! Thanks!

**Comment by pal1000** [comment]
Requirements to fully address #19:
- [x] Manually add version information to binaries (expired);
- [x] Temporary use and maintain manually created resource script files; 
- [ ] Create a resource script file generator;
- [ ] Create, compile and attach to binaries resources created with generator using ResourceHacker command line options.
