### ISSUE TITLE
How to uninstall Mesa3D from Win10?

### ISSUE THREAD

**Issue by Milliath** [pal1000/mesa-dist-win#20]
I just upgraded my pc with a new mobo, RAM and CPU. The CPU is Ryzen 5 2400G with Vega 11 onboard. Thing is, my monitor is a VGA D-sub, which is not supported by my mobo (Gigabyte GA-A320M-H), so when I install video drivers, the screen goes to noise after 2 seconds, then blacking it and it starts again. I tried to install Mesa3D instead and wasn't happy with the results and decided to remove it. Question is - _how_ do i remove it?

**Comment by pal1000** [comment]
If you used system wide deployment tool, run it again and select option 7 - Remove system-wide deployments (uninstall).

For per-applications deployment, if you did any, you have to do it manually for each program; remove DLLs with shortcut icons from installation folder. It should be easy as Mesa3D has pretty specific DLL filenames:
- opengl32.dll;
- graw.dll;
- osmesa.dll;
- swrAVX.dll;
- swrAVX2.dll.

**Comment by Milliath** [comment]
Thanks, forgot I had that option in the list.
I was playing Minecraft (which is pretty playable at minimum settings), but. again, the cause of my problem is not the drivers or Mesa3D, it's the incompatibility of old monitor and newer graphics. The screen behaves normally without drivers _and_ with Mesa.

**Comment by cesss** [comment]
This should be in the documentation. When you install Mesa3D, you want to know the procedure for uninstalling it, just in case you need to do so.
