### ISSUE TITLE
Cannot create newer OpenGL contexts.

### ISSUE THREAD

**Issue by AHUMANTHATISHUMAN** [pal1000/mesa-dist-win#21]
Using Mesa, I am unable to create an OpenGL context past version 3.3. Any later version gives the error: "WGL: Failed to create OpenGL context". Even though the normal driver supports OpenGL 4.3, using Mesa I can only use up to version 3.3. The OpenGL version is given as "OpenGL version 3.1 Mesa 19.0.2". Isn't Mesa 19.0.2 supposed to implement up to OpenGL 4.5?

Using [glewinfo](https://sourceforge.net/projects/glew/files/glew/2.1.0/glew-2.1.0-win32.zip/download), it shows that OpenGL 4.1-4.5 are missing (although the extensions from those versions are not). However, I am still unable to create an OpenGL 4.6 context, which is marked as "OK".

**Comment by pal1000** [comment]
Software rendering stack (softpipe, llvmpipe and swr), which is the only thing we have on Windows only supports OpenGL 3.3 in core profile and forward compatible context and 3.1 in compatibility profile.  Only Intel, AMD and Nvidia hardware acceleration drivers (i965, radeonsi and nvc0) support OpenGL 4.5, see [mesamatrix](https://mesamatrix.net/).  You have to use MESA_GL_VERSION_OVERRIDE and MESA_GLSL_VERSION_OVERRIDE to use those incomplete OpenGL contexts.

**Comment by AHUMANTHATISHUMAN** [comment]
I tried using `set MESA_GL_VERSION_OVERRIDE=4.6FC` and now I can create an OpenGL 4.5 context (which is supported natively) but not 4.6. I haven't yet tried with the device supporting 4.3. Is there any reason why I can only create a 4.5 context. Also, how do you specify the hardware acceleration devices?

**Comment by pal1000** [comment]
OpenGL 4.6 is not advertised by any driver yet, even GPU accelerated ones that are only available on Linux lack it so I don't know. Though I was able to get Cemu to run which uses OpenGL 4.6 so I don't  know what's going on see #18.
