### ISSUE TITLE
GLSL 4.20 is not supported.

### ISSUE THREAD

**Issue by amayra** [pal1000/mesa-dist-win#24]
```
NV_depth_buffer_float: not supported
[06:30:28] Error/Warning in vertex shader:
[06:30:28] 0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
```

can you help please with this error ?

**Comment by pal1000** [comment]
Mesa3D on windows supports only software rendering stack so you only get OpenGL 3.1 in compatibility profile and 3.3 in core profile by default. However you can set MESA_GL_VERSION_OVERRIDE and MESA_GLSL_VERSION_OVERRIDE to overcome this limitation:
https://github.com/pal1000/mesa-dist-win#opengl-context-configuration-override
