### ISSUE TITLE
Publish prebuilts as archive, not as self-extracting exe

### ISSUE THREAD

**Issue by PhilLab** [pal1000/mesa-dist-win#27]
Makes it easier to integrate in automated pipelines like e.g. [VCPKG](https://github.com/Microsoft/vcpkg/) and looks less "shady" than executing an exe. Developer mostly know archives and how to extract them.

**Comment by pal1000** [comment]
All right @PhilLab done as requested. 19.1.4 binaries are archive only, no SFX.

**Comment by PhilLab** [comment]
@pal1000 Thanks a lot 👍
