### ISSUE TITLE
Request for a Mesa 20.0rc1 build for testing new SWR tesselation support..

### ISSUE THREAD

**Issue by oscarbg** [pal1000/mesa-dist-win#29]
Hi,
I know isn't yet released but asking already in case I forget later.. mainly motivated on testing tesselation apps like Tessmark (requires env vars MESA_GL_VERSION_OVERRIDE=4.1 & MESA_GLSL_VERSION_OVERRIDE=410 to start_tessmark_windowed_1024x640)..

https://cgit.freedesktop.org/mesa/mesa/commit/?id=f09c466732e4a5b648d7503787777c926dd93c29

**Comment by pal1000** [comment]
Okay.

**Comment by donizettilorenzo** [comment]
Thanks!

**Comment by oscarbg** [comment]
thanks!

**Comment by pal1000** [comment]
Pre-release is live. Closing.

**Comment by oscarbg** [comment]
thanks..
tesselation works as expected but fixed small typo (4.1FC):
```
set GALLIUM_DRIVER=swr
set MESA_GL_VERSION_OVERRIDE=4.1FC
set MESA_GLSL_VERSION_OVERRIDE=410
start GpuTest_GUI.exe
```

**Comment by donizettilorenzo** [comment]
RC3 please!

**Comment by pal1000** [comment]
You are still only interested in swr. right?

**Comment by pal1000** [comment]
RC3 pre-release posted, MSVC only.
