### ISSUE TITLE
Request for master build (20.2dev) with MSAA LLVMpipe  support..

### ISSUE THREAD

**Issue by oscarbg** [pal1000/mesa-dist-win#33]
Hi,
don't know if it's much to ask for, but anyway interested to try new LLVMpipe MSAA 4x support merged recently along with three new exts supported:
(mesamatrix)
2 days | llvmpipe: enable ARB_sample_shading
2 days | llvmpipe: enable GL_ARB_shader_texture_image_samples
2 days | llvmpipe: simple texture barrier implementation. (GL_ARB_texture_barrier)

Also few ours ago "wgl: add MSAA support" was merged fixing/adding that support to Windows..
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4926

even Phoronix writed an article:
https://www.phoronix.com/scan.php?page=news_item&px=LLVMpipe-4x-MSAA-Bits

thanks anyway for your work!

**Comment by pal1000** [comment]
Done.

**Comment by oscarbg** [comment]
many thanks!

**Comment by oscarbg** [comment]
Hi @pal1000 ,
can ship a 20.2rc1 build? to test llvmpipe 4.3 support..
thanks..

**Comment by pal1000** [comment]
It's almost ready.
