### ISSUE TITLE
Interested in shipping CLonD3D12 and GLonD3D12 on your dist?

### ISSUE THREAD

**Issue by oscarbg** [pal1000/mesa-dist-win#34]
Hi,
just forgot to ask about your interest on this announcement of CL and GL over D3D12:
"https://www.collabora.com/news-and-blog/news-and-events/introducing-opencl-and-opengl-on-directx.html"
no hurry, just asking.. as right now isn't even merged on mesa master branch.. but that's the plan eventually.. seems right now implementation is changing fast : https://gitlab.freedesktop.org/kusma/mesa/-/merge_requests

really just opening issue so I get notified of eventual news on this .. :-)
thanks..

**Comment by oscarbg** [comment]
Hi,
just pointing also there is a first open merge request for GLonD3D12 (seems complete support should need some more patches):
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7477
maybe before end of the year support is in place..
thanks..

**Comment by pal1000** [comment]
I don't think so because 20.3 was branched, so GLonD3D12 won't be available until 21.0.
I'll look into it though after merge and when CI stuff is in place.

**Comment by pal1000** [comment]
This comment applies here as well: https://github.com/pal1000/mesa-dist-win/issues/30#issuecomment-759743978

**Comment by oscarbg** [comment]
yep,
will test once a GLonD3D12 build is posted..
similary to my answer in https://github.com/pal1000/mesa-dist-win/issues/30#issuecomment-760986695 assuming assuming regular builds starting with 21.0 release will have GLonD3D12 support included by default you can close issue..
maybe keep open this issue as from your comment seems CLonD3D12 will not be included in initial release but that's fine as much more important is GLonD3D12 and seems much more work to build CLonD3D12 than GLonD3D12 (CL requiring a LLVM build)..

**Comment by pal1000** [comment]
A [pre-release with GLonD3D12](https://github.com/pal1000/mesa-dist-win/releases/tag/21.0.0-rc1-msvc) is out. It has a lot of known issues just like the one with zink.

**Comment by pal1000** [comment]
I reported the x86 32-bit problem [upstream](https://gitlab.freedesktop.org/mesa/mesa/-/issues/4108).

**Comment by pal1000** [comment]
> It seems much more work to build CLonD3D12 than GLonD3D12 is required (CL requiring a LLVM build).

Indeed, it actually requires a far more expanded LLVM build than other drivers.
###  CLonD3D12 roadmap
LLVM build with
- [x] Clang + LLD (eb27094ce, 8d3b5768, c333afffd)
- [x] SPIRV Translator (bce3b471)
- [ ] libCLC

and [ ] SPIRV tools.

**Comment by oscarbg** [comment]
curious if 21.3 release will include clond3d12 support seeing your recent clover effort..

**Comment by pal1000** [comment]
Finally it made it into 21.3.6-2.
