### ISSUE TITLE
How to disable AVX instruction set in opengl32.dll compilation

### ISSUE THREAD

**Issue by fabceolin** [pal1000/mesa-dist-win#4]
I am getting illegal instruction when I trying to use opengl32.gll
From depends_x64
00:00:21.282: Second chance exception 0xC000001D (Illegal Instruction) occurred in "%DIR%\OPENGL32.DLL" at address 0x00007FF975EDB0E3 by thread 1.

Here I saw about AVX instruction set:
https://www.gamedev.net/forums/topic/648813-illegal-instruction-possible-causes/

How can I change the instruction set in opengl32.dll compilation? (maybe removing the AVX instruction set)

**Comment by pal1000** [comment]
I think you need to ask for help on Mesa-dev mailing list. 
What program it happens with?
Did you use my build or you built it yourself?

**Comment by fabceolin** [comment]
I tried your build first, without success and now I am trying to build myself.

We are testing using our software, based in VTK.

**Comment by pal1000** [comment]
AVX2 without AVX is definitely an unsupported configuration. I have doubts this will be fixed by Mesa3D developers. Sorry, but all you can do is build it yourself on that awkward configuration of yours and see what happens.
