### ISSUE TITLE
Vallium (Mesa Vulkan CPU backend)

### ISSUE THREAD

**Issue by oscarbg** [pal1000/mesa-dist-win#40]
Hi,
seems Vallium was merged into Mesa last month:
https://www.phoronix.com/scan.php?page=news_item&px=Mesa-VALLIUM-Merged
currently it's in Mesa master (so should be in 20.3)..
don't know current status but might be very immature at this point..
anyway, any interest to also ship Vallium Vulkan CPU driver in your Win Mesa builds?

thanks..

**Comment by pal1000** [comment]
Yes, but it's too early as you stated. I know Mesa Vulkan code doesn't consider Windows yet, so don't expect this anytime soon. Though surprises can happen, like the [patch which made swr build with mingw](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/6532) a reality. That patch came out of the blue.

**Comment by oscarbg** [comment]
thanks for info.. will keep it open..

**Comment by oscarbg** [comment]
Hi,
just pointing that things have progressed well on this front, as there is now an issue, with corresponding merge request, adding Windows support to Vallium (now known as lavapipe)..

https://gitlab.freedesktop.org/mesa/mesa/-/issues/3602
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7208

from issue seems building Lavapipe on Windows should be as easy as:
meson -Dgallium-drivers=swrast,swr -Dvulkan-drivers=swrast 
(don't know why SWR is needed, but as you build too, no problem)

also driver is getting mature as being tested under Vulkan CTS:
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7499

no hurry for a build just pointing out the news.. maybe as soon patch is merged can be considered..
thanks for your work..

**Comment by pal1000** [comment]
I saw lavapipe win32 progress as well.
