### ISSUE TITLE
20.3 RC build release?

### ISSUE THREAD

**Issue by donizettilorenzo** [pal1000/mesa-dist-win#42]
Please! 👍

https://www.phoronix.com/scan.php?page=news_item&px=Mesa-20.3-RC1-Released&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Phoronix+%28Phoronix%29

**Comment by pal1000** [comment]
@donizettilorenzo Mesa 20.3 doesn't have anything to stand out on Windows.
llvmpipe GL4.5 was backported to 20.2 and lavapipe doesn't support Windows yet.

21.0 will be far more interesting with lavapipe and zink having Windows support work in progress and the addition of GLonD3D12 and CLonD3D12 as drivers intended firstly for Windows.

I'll build it anyway soon.

**Comment by donizettilorenzo** [comment]
Thanks man, much obliged!

**Comment by pal1000** [comment]
Done.
