### ISSUE TITLE
MESA 21 OpenGL-DXIL: forced negative LoD Bias?

### ISSUE THREAD

**Issue by donizettilorenzo** [pal1000/mesa-dist-win#44]
Why the image presented to the output (monitor) seems like processed by a sharpening filter?
Mipmap LoD management issues?

PNG (screenshot taken via STAMP button, load the FULL RESOLUTION version ) -> https://ibb.co/XSTFsdG

No problem with LLVMPipe ! Output is regular!

**Comment by pal1000** [comment]
Please report rendering bugs directly [upstream](https://gitlab.freedesktop.org/mesa/mesa/-/issues).  You can also tag me there as I use same handle.
