### ISSUE TITLE
Missing files in deploy

### ISSUE THREAD

**Issue by adrianre12** [pal1000/mesa-dist-win#47]
I am trying to use mesa-dist-win on github CI runners. To do so I need to automate the deploy script.
I have found that in the systemwidedeploy.cmd script it tries to copy some files that do not exist in the package.
In the osmesa section, it has 
`@if "%deploychoice%"=="3" set osmesatype=gallium
@if "%deploychoice%"=="4" set osmesatype=swrast
@IF /I %PROCESSOR_ARCHITECTURE%==X86 copy "%mesaloc%\x86\osmesa-%osmesatype%\osmesa.dll" "%windir%\System32"
@IF /I %PROCESSOR_ARCHITECTURE%==AMD64 copy "%mesaloc%\x86\osmesa-%osmesatype%\osmesa.dll" "%windir%\SysWOW64"
@IF /I %PROCESSOR_ARCHITECTURE%==AMD64 copy "%mesaloc%\x64\osmesa-%osmesatype%\osmesa.dll" "%windir%\System32"`

But in the package, the directories osmesa-galium and osmesa-swrast do not exist.  If they did exist these lines would overwrite the osmesa.dll that had already been copied.

**Comment by pal1000** [comment]
> I have found that in the systemwidedeploy.cmd script it tries to copy some files that do not exist in the package.

Some packages have those files e.g. 

> But in the package, the directories osmesa-galium and osmesa-swrast do not exist. If they did exist these lines would overwrite the osmesa.dll that had already been copied.

This is avoided during distribution creation unless you purposely mess with the package.

I'll fix those " harmless" errors for the sake of aesthetics, though.

**Comment by adrianre12** [comment]
OK, thanks for the quick reply.
