### ISSUE TITLE
Support for unattended installation

### ISSUE THREAD

**Issue by adrianre12** [pal1000/mesa-dist-win#48]
I think being able to install via scripts would be a very useful feature. As it is now it is not possible to use the deploy scripts in provisioning systems. I am currently working with Github runners. As these are VMs created on-demand they need setting up at each run via scripts. 
I did try and modify the systemwidedeploy.cmd to accept an argument (1 - 6) but it was getting very complicated bypassing   the "pauses" and "goto deploy"
It would be great if you could add a script that accepts an argument instead of the menu based install.

**Comment by pal1000** [comment]
I'll implement unattended installation to system-wide deployment tool. It shouldn't be too hard. I did something like this at a bigger scale with swiftshader.

**Comment by adrianre12** [comment]
Sry for the delay I did not get a notification of your comment.
I have tried it and it is causing the job to fail due to the exit code being 1
I don't understand the function of 
`@set deployresult=1`
and the
`@IF NOT "%1"=="" CHOICE /N /T %deployresult% /C y /D y >nul 2>&1`
Looking at [https://www.computerhope.com/choicehl.htm#:~:text=The%20choice%20command%20allows%20users,the%20MS%2DDOS%20set%20command.](URL) I think the CHOICE command is set to have one choice 'y' with a default of 'y' and a timeout set to the value of defaultchoice = 1. After 1 second CHOICE is setting ERRORLEVEL=1
When this is set at the end of the batch it results in it exiting as failed. It looks like all the other CHOICE lines are redundant as they are immediately followed by a GOTO exit.

I have tried removing all the CHOICE lines except for in update: where it is reporting an error due to no mesa drivers and it ran successfully.

I have done some googling and it seems a way to handle errors in the install would be to add `|| EXIT /B 1` to every line that is important.

**Comment by pal1000** [comment]
I didn't know CHOICE is poisoning ERRORLEVEL. I use CHOICE to insert customizable delays that replaces pauses from interactive mode. It looks like I need a new approach.

**Comment by pal1000** [comment]
Found a new approach using [timeout](https://ss64.com/nt/timeout.html). Hopefully things will be better this time.

**Comment by adrianre12** [comment]
There is a problem with timeout on headless machines. I get the error
`ERROR: Input redirection is not supported, exiting the process immediately.`
Which causes the script to terminate with an error, odd that pause was fine with the redirect but timeout is not. I have tried running it in different shells but no success.
I am not very familiar with batch files, but I can not see a reason to have the timeout in the unattended flow. I tried it with all the timeout lines removed and it runs OK.

What do you think of adding error handling as I mentioned before?
```
@echo off

IF NOT "%1"=="" dir something fails || goto error
goto exit

:error
echo something failed
EXIT /B 1

:exit
echo normal exit
```

If you run this with an argument it causes an error and it terminates with ERRORLEVEL=1 .

**Comment by pal1000** [comment]
Maybe unattended shells  don't like the extra space from `> nul`, preferring `>nul` instead. Please retry with latest master.

**Comment by adrianre12** [comment]
But the error is Input redirection, and I earlier I did try it without the > nul with the same error.

**Comment by adrianre12** [comment]
I tried the latest and get the same error

**Comment by pal1000** [comment]
I eliminated delay support completely.

**Comment by adrianre12** [comment]
When do you think this will make it into a release?

**Comment by pal1000** [comment]
1-2 days after Mesa3D release. It could be with 20.3.5 or 21.0.0, whichever comes first.

**Comment by pal1000** [comment]
I did 21.0.0-rc5 to incorporate this feature as 21.0.0 is late and most Windows specific regressions are now addressed.
