### ISSUE TITLE
Missing DXIL binaries

### ISSUE THREAD

**Issue by InflexCZE** [pal1000/mesa-dist-win#49]
I can't seem to find `spirv_to_dxil` executable and/or `libspirv_to_dxil` in the release packages.

In the source tree it would be these build targets: 
https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/src/microsoft/spirv_to_dxil/meson.build

Do you build only drivers and this is intentional or can I possibly ask for these two to be added as well?

**Comment by pal1000** [comment]
I didn't add spirv to dxil support yet due to very high complexity and overall build time growing dramatically.

**Comment by InflexCZE** [comment]
After a bit of hassle I managed to compile my own bins and realized that statement from one of the devs 
`It barely works for anything at the moment :)` is pretty accurate 😄 
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/8043

`spirv2dxil.exe` failed to digest even very basic compute shaders for me, so I consider it a dead end for now.
Feel free to close the issue.

For any future readers, if you want to build your own Mesa DXIL bins follow this guide for dependency and compiler setup:
https://docs.mesa3d.org/install.html

Then go ahead with following command from `x64 Native tools cmd`
```
meson builddir --backend=vs -Dspirv-to-dxil=true
```

It will generate `mesa.sln` for you into `builddir` which you can build via `msbuild` or VS.
