### ISSUE TITLE
POCL

### ISSUE THREAD

**Issue by donizettilorenzo** [pal1000/mesa-dist-win#5]
I post the request as an "issue" 'cause it's the only way to contact pal1000 through github :-D

Man, can you do the same (windows binaries) for POCL now @1.0? https://github.com/pocl/pocl

**Comment by pal1000** [comment]
This is not a priority at the moment. Any particular reason you don't want to use Intel Graphics Driver bundled OpenCL CPU runtime, Intel OpenCL SDK or AMD APP SDK, they go up to OpenCL 2.1. BTW. I looked at the quick build script. It uses the really old MSVC 2013 so I need to tweak it for MSVC 2017 and hope it works.

**Comment by donizettilorenzo** [comment]
No need to haste!
Not a particular reason, only to have an Open Source and
community-maintained alternative to test :)

Thanks for the answer :)

2017-12-20 16:55 GMT+01:00 pal1000 <notifications@github.com>:

**Comment by pal1000** [comment]
Well, this doesn't look good: pocl/pocl#374.
