### ISSUE TITLE
Can't understand "openglon12.dll" function

### ISSUE THREAD

**Issue by donizettilorenzo** [pal1000/mesa-dist-win#55]
If the deployment tool (per app) just creates a link to opengl32, libglapi and dxil (or you manually copy these dll only in the main exe app folder) what is the function of bundled "openglon12.dll" ?
In the user guide there's no value for "gallium_driver" when you want to force d3d12. Is it "d3d12" just like "llvmpipe" for LLVMPipe or "zink" for Vulkan ?

**Comment by pal1000** [comment]
> If the deployment tool (per app) just creates a link to opengl32, libglapi and dxil (or you manually copy these dll only in the main exe app folder) what is the function of bundled "openglon12.dll" ?

That probably only helps on systems with D3D12 but without OpenGL.  It was entirely Microsoft' decision to create it to have a small DLL that only contains OpenGL and OpenCL on D3D12

> In the user guide there's no value for "gallium_driver" when you want to force d3d12. Is it "d3d12" just like "llvmpipe" for LLVMPipe or "zink" for Vulkan ?

Yes and sorry for being late with updating docs.

**Comment by donizettilorenzo** [comment]
Thanks!
