### ISSUE TITLE
Mesa 21.0.1 (MinGW) DLL files don't appear to hook or work at all with OpenGL applications

### ISSUE THREAD

**Issue by BlohoJo** [pal1000/mesa-dist-win#56]
I'm on Windows 10 Pro x64 2004. GPU-less VPS.

All Mesa versions work fine for me up to version 20.3.4. I use the MinGW versions.

I usually only need to copy `opengl32.dll` and `libglapi.dll` into the directory of the application that I want to run and it works fine. (Older Mesa versions usually only need `opengl32.dll` and that's it.)

Every version after 20.3.4 of course returns the missing `vulkan-1.dll` error.

I tried the latest version 21.0.1 which doesn't say anything about the Vulkan issue ([mesa3d-21.0.1-release-mingw.7z](https://github.com/pal1000/mesa-dist-win/releases/download/21.0.1/mesa3d-21.0.1-release-mingw.7z)), but it doesn't appear to work at all. Applications that require OpenGL behave exactly as if the Mesa DLL files are *NOT* present, even though they are. In other words, if I just try to run an application that requires OpenGL without copying the Mesa files in, it will give the exact same errors that it does when the Mesa files for version 21.0.1 *are* copied in.

Again, everything works fine with Mesa versions 20.3.4 and earlier.

Not sure if it's just me or not, also not sure what additional info I should be posting. :face_with_head_bandage:

**Comment by donizettilorenzo** [comment]
Read the guide, Vulkan RT is always needed.

**Comment by BlohoJo** [comment]
But there is no Vulkan device installed on the system. It's a GPU-less VPS.

Very confused if I need the [runtime](https://vulkan.lunarg.com/sdk/home), or [SwiftShader](https://dev.azure.com/bontarka/swiftshader-dist-win/_build?view=runs), or both.

Sounds like for now I should just stick to 20.3.4 and lower to avoid headaches, until I need to try to run something that uses Vulkan I guess. :confused:

**Comment by pal1000** [comment]
> Every version after 20.3.4 of course returns the missing `vulkan-1.dll` error.

Yes, you need Vulkan runtime, fortunately no Vulkan device is needed, see
https://gitlab.freedesktop.org/mesa/mesa/-/issues/3855

**Comment by BlohoJo** [comment]
Solution: Starting from Mesa versions ***after*** 20.3.4, [vulkan-1.dll](https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-runtime-components.zip?u=) is now also required. Copy the file into the application directory along with the Mesa files, or copy somewhere into a system path (i.e., C:\Windows\System32).
