### ISSUE TITLE
How can I run OpenGL3.2 application on GL2.0 device

### ISSUE THREAD

**Issue by xtexChooser** [pal1000/mesa-dist-win#57]
Mesa3d looks like supported rendering by software, so I want to run Minecraft on OpenGL2.0 computer.
Minecraft is required OpenGL 3.2 in the latest snapshot version.
I setted the environment variables:
MESA_GL_VERSION_OVERRIDE: 4.6COMPAT
MESA_GLSL_VERSION_OVERRIDE: 460
LIBGL_ALWAYS_SOFTWARE: true
But the game tell me:
```
A forward compatible OpenGL context requested but WGL_ARB_compatibility is unavailable
```
The AIDA64 tell me:
The ICD is mesadrv
but OpenGL version is 2.1.0
The max viewport size is 4096*4096 and GL_ARB_compatibility is not supported.
My graphic card is only supported OpenGL 2.0
I am using Windows7 32-bits

**Comment by pal1000** [comment]
Try with
````
MESA_GL_VERSION_OVERRIDE: 3.3
MESA_GLSL_VERSION_OVERRIDE: 330
````
and drop `LIBGL_ALWAYS_SOFTWARE: true`. That only applies to GLonD3D12 which I doubt it can run properly on Win7.

**Comment by xtexChooser** [comment]
Thanks

**Comment by xtexChooser** [comment]
I installed Mesa3d to the Java Runtime.
I installed it to the system before.

**Comment by FizzyYT123** [comment]
I might sound Stoopid saying this but is this for windows or Linux and where do I put the Mesa override variables...

**Comment by pal1000** [comment]
> I might sound Stupid saying this but is this for windows or Linux?

Windows.
> and where do I put the Mesa override variables

You write a filename .cmd file that in addition to setting Mesa3D environment variables, it also starts your program of choice. Alternatively you can set  Mesa3D environment variables in `Edit environment variables for your account` in Start search.

**Comment by ArcTici7** [comment]
thx for the tip but can you help me wirte a .cmd script?? I want to run Minecraft Launcher with mesa env variables...

**Comment by pal1000** [comment]
For something like Minecraft you probably don't need to set OpenGL context control environment variables anymore. llvmpipe support OpenGL 4.5 on all contexts. So just deploying  should be enough.
