### ISSUE TITLE
Using OSMesa on Windows

### ISSUE THREAD

**Issue by vadimwind** [pal1000/mesa-dist-win#6]
I try to use your dll for offscreen rendering under Windows with .net core.

The following code works well under Linux, but fails under Windows: no exceptions, but glReadPixels returns buffer with zeros.

```
public static void Main(string[] args)
{
	int w = 800;
	int h = 600;
	int length = w * h * 4;
	byte[] buffer = new byte[length];
	IntPtr pnt = Marshal.AllocHGlobal(Marshal.SizeOf(buffer[0]) * length);

	var ctx = OSMesaCreateContext(GL.GL_RGBA, IntPtr.Zero);

	try
	{
		Marshal.Copy(buffer, 0, pnt, length);

		if (!OSMesaMakeCurrent(ctx, pnt, GL.GL_UNSIGNED_BYTE, 800, 600))
		{
			Console.WriteLine("OSMesaMakeCurrent failed!");
			return;
		}

		GL.glMatrixMode(GL.GL_PROJECTION);
		GL.glLoadIdentity();
		GL.glOrtho(0.0, 1.0f, 0.0, 1.0, 0.0, 1.0);
		GL.glMatrixMode(GL.GL_MODELVIEW);
		GL.glLoadIdentity();

		GL.glBegin(GL.GL_TRIANGLES);
		GL.glColor3f(1.0f, 0.0f, 0.0f); GL.glVertex2f(0.0f, 0.0f);
		GL.glColor3f(0.0f, 1.0f, 0.0f); GL.glVertex2f(0.5f, 1.0f);
		GL.glColor3f(0.0f, 0.0f, 1.0f); GL.glVertex2f(1.0f, 0.0f);
		GL.glEnd();

		GL.glReadPixels(0, 0, w, h, GL.GL_RGBA, GL.GL_UNSIGNED_BYTE, pnt);

		Marshal.Copy(pnt, buffer, 0, length);

		using (Image<Rgba32> image = Image.LoadPixelData<Rgba32>(buffer, w, h))
		{
			image.Save("test.bmp", new BmpEncoder());
		}
	}
	finally
	{
		OSMesaDestroyContext(ctx);
		Marshal.FreeHGlobal(pnt);				
	}

	Console.WriteLine("OK");
}

[DllImport("osmesa-gallium")]
public static extern IntPtr OSMesaCreateContext(uint format, IntPtr sharelist);
[DllImport("osmesa-gallium")]
public static extern IntPtr OSMesaCreateContextExt(uint format, int depthBits, int stencilBits, int accumBits, IntPtr sharelist);
[DllImport("osmesa-gallium")]
public static extern bool OSMesaMakeCurrent(IntPtr hdc, IntPtr buffer, uint type, int width, int height);
[DllImport("osmesa-gallium")]
public static extern void OSMesaDestroyContext(IntPtr hdc);
```
I put opengl32.dll and osmesa-gallium.dll into my bin folder.

I would be grateful if you could tell any suggestions what I could miss

**Comment by pal1000** [comment]
Make sure you rename osmesa-gallium.dll to osmesa.dll before using. The same stands for osmesa-swrast.dll too. The build script renames them so that they can coexist on same folder. Though probably I should create folders for each to avoid filename collision.  I'll work on this and enhancement may land on next release.

**Comment by vadimwind** [comment]
I renamed osmesa-gallium.dll to osmesa.dll and tried both methods - with symlink and hard copy - I got the same result.

I added glGetString call after OSMesaMakeCurrent

```
unsafe
{
	var s = new string((sbyte*)GL.glGetString(GL.GL_RENDERER));			
	Console.WriteLine(s);
}	
```
and see NULL under Windows and "Mesa OffScreen" under Linux.

It's looks like OSMesaMakeCurrent returns true, but not really initialized opengl context under Windows.

**Comment by pal1000** [comment]
Can you try with osmesa-swrast? Make sure you set GALLIUM_DRIVER=softpipe to use it.  However osmesa-swrast is capped at GL 2.1 and gallium at GL 3.3 with core profile. You can try to go above of course as you already demonstrated you have the know how.

**Comment by vadimwind** [comment]
I tried the following:
1. Osmesa-swrast with GALLIUM_DRIVER=softpipe - the same result, not working
2. Both osmesa dlls with logging using GLIntercept
GLIntercept log also showed that OSMesaMakeCurrent did't really initialize opengl context
```
Function glGetString is being called before context creation
Call to glGetString made outside of context/init
Function glMatrixMode is being called before context creation
Call to glMatrixMode made outside of context/init
...
```
3. Your OpenGL32.dll works fine with hidden window + wglCreateContext + wglMakeCurrent, glGetString(GL_RENDERER) returns "llvmpipe (LLVM 5.0, 256 bits)"

Also I tried to use MESA_DEBUG, ST_DEBUG, MESA_LOG_FILE environment variables, but it seems not working in release version of the dlls.
```
set MESA_DEBUG=1
set MESA_LOG_FILE=c:\temp\log.txt
set ST_DEBUG=mesa
set LIBGL_DEBUG=verbose
set MESA_VERBOSE=1
```

Could you please compile debug versions also?

**Comment by pal1000** [comment]
Here you go. Quickly made 64-bit debug build without LLVM.  This only contains softpipe, osmesa gallium and osmesa swrast.
[mesa-17.3.5-noLLVM-debug.zip](https://github.com/pal1000/mesa-dist-win/files/1757680/mesa-17.3.5-noLLVM-debug.zip)
You should also be aware of this [upstream issue](https://bugs.freedesktop.org/show_bug.cgi?id=94491).
Beside my Visual Studio native build there is [MSYS2](https://sourceforge.net/projects/msys2/files/REPOS/MINGW/) which has a cross-compiled version of Mesa with GCC. It contains softpipe+llvmpipe, osmesa gallium and graw. No osmesa swrast. They had problems with 32-bit builds for about 2-3 years but they sorted them up when they built 17.3.3 through pure luck. Unfortunately they don't update often, they are still at 17.3.3. I know 7-zip can extract xzipped tarballs from there.

**Comment by vadimwind** [comment]
Thank you

Debug version prints only "stw_init" in my case, so debug environment variables did not give any new info how to solve my problem.

I also tried to make build according you guidelines

```
scons build=debug platform=windows machine=x86_64 libgl-gdi osmesa
```

but got error

```
scons: Reading SConscript files ...
Checking for MSVC ...  yes
Checking for Clang ...  no
Checking for win_flex ...  yes
Checking for win_bison ...  yes
scons: Found LLVM version 5.0
Checking for X11 (x11 xext xdamage >= 1.1 xfixes glproto >= 1.4.13 dri2proto >= 2.8)... no
Checking for XCB (x11-xcb xcb-glx >= 1.8.1 xcb-dri2 >= 1.8)... no
Checking for XF86VIDMODE (xxf86vm)... no
Checking for DRM (libdrm >= 2.4.75)... no
scons: done reading SConscript files.
scons: Building targets ...
...
glsl_parser_extras.cpp
src\compiler\glsl\glsl_parser.yy(978): error C2666: 'operator !=': 2 overloads have similar conversions
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\guiddef.h(197): note: could be 'bool operator !=(const GUID &,const GUID &)'
C:\Projects\mesasrc\mesa\src\compiler\glsl\ast.h(477): note: or       'bool operator !=(const ast_type_qualifier::bitset_t &,const ast_type_qualifier::bitset_t &)' [found using argument-dependent lookup]

```

**Comment by pal1000** [comment]
I think when you grabbed Mesa code with git you might have picked other branch. one that simply fails to build. That error doesn't indicate anything else. Anyway, this looks to me more and more as an upstream bug.
You can ask for help at mesa-dev mailing list. Also on freedesktop.org bug tracker, but you should start with the mailing list. You'll likely get help faster.

**Comment by vadimwind** [comment]
I solved the issue!

* stable mesa branch 17.3 compiles well (but only release profile)
* opengl32.dll is not necessary for working with osmesa, osmesa.dll is enough
* the main thing: gl* methods should be imported from osmesa.dll, not from opengl32.dll
* as you mentioned before osmesa gallium build is missing a lot of gl* symbols
* my test program works well without setting any environment variables

**Comment by clienthax** [comment]
It seems this might be an issue again, I'm seeing a similar thing on the latest builds.
