### ISSUE TITLE
works but breaks external controller

### ISSUE THREAD

**Issue by R-Soul99** [pal1000/mesa-dist-win#62]
Used this on Ableton Live yesterday, as there's a problem with that program where Max4Live plugins don't give visual feedback which is related to OpenGL.  

It did work, but also brought up errors related to the LCD display of the attached ableton Push 2 device:

"the procedure entry point ?getcurrentcontext@egl@@YAPEAXXZ could not be located in the dynamic link library"

So it seems you can either have your plugins give visual feedback but no display on the Push controller, or have the Push display work but not the plugins :(

I used the per-application deployment, pointed at abletonlive.exe.  Is there a way to apply this just to the plugins while leaving the external device alone?  I ended up having to re-install ableton to get my controller screen working again.

**Comment by pal1000** [comment]
> I used the per-application deployment, pointed at abletonlive.exe. Is there a way to apply this just to the plugins while leaving the external device alone?

Probably no. It would only work if plugins were available as exe files and in aseparate folder from main exe.

**Comment by R-Soul99** [comment]
thanks @pal1000 - i'll have another look later as i think there might be a separate .exe for Max4Live plugins (Ableton bought Max a while back but it might still have its own launcher).  Everything related to the controller is linked to the main program.

I may also have another go at applying it to abletonlive.exe then cycling through the different openGL drivers as you suggested - or would that involve re-installing the main program between every attempt?  I presume the Push controller doesn't use openGL because it normally works and my laptop is old and on Intel HD 3000 drivers which don't support it, but something is interfering with it when using Mesa3D.

**Comment by pal1000** [comment]
> I may also have another go at applying it to abletonlive.exe then cycling through the different openGL drivers as you suggested - or would that involve re-installing the main program between every attempt?

No, it won't.

**Comment by R-Soul99** [comment]
Hey, I managed to get it working using (your?) old video regarding opengl support for intel hd 3000.  For some reason that enabled the visuals for Max devices AND retained the Push 2 display - thanks!
