### ISSUE TITLE
Get worse performance than the official driver

### ISSUE THREAD

**Issue by shu307** [pal1000/mesa-dist-win#64]
First of all, thanks to this project for making it easy for us to install mesa on windows.
I have a rx 5700 running on win10. As we all know,  the AMD official driver's  OpenGL performance is horrible.
But, with the official driver I have 25 frames, and with mesa i get only 20 frames. 
Is this normal?

**Comment by pal1000** [comment]
What package did use MSVC or MinGW. MSVC package might run faster on D3D12 enabled systems by default. On MinGW package you can try zink driver via `set GALLIUM_DRIVER=zink`.
