### ISSUE TITLE
Should system-wide deployment replace opengl32.dll ?

### ISSUE THREAD

**Issue by howff** [pal1000/mesa-dist-win#66]
I see that the release bundle includes `opengl32.dll` but the system-wide deployment script copies it to `System32\mesadrv.dll` so how does it get called?  Surely it should overwrite the microsoft `opengl32.dll` ?  My use-case is trying to get a collection of existing applications (eg. 3DSlicer, ITK SNAP, MITK, etc) working inside a Windows Server 2012 VM hosted by Hyper-V viewed through a remote desktop, which presents only OpenGL-1.1.

**Comment by pal1000** [comment]
> I see that the release bundle includes `opengl32.dll` but the system-wide deployment script copies it to `System32\mesadrv.dll` so how does it get called?

In addition to being copied it is also registered in `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers\MSOGL` and `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers\MSOGL` which tells Windows to load it when there is no OpenGL acceleration available.

> My use-case is trying to get a collection of existing applications (eg. 3DSlicer, ITK SNAP, MITK, etc) working inside a Windows Server 2012 VM hosted by Hyper-V viewed through a remote desktop, which presents only OpenGL-1.1.

OpenGL 1.1 software renderer only is the exact use case for it.

> Surely it should overwrite the microsoft `opengl32.dll` ?

That's a bad idea.

**Comment by howff** [comment]
Thank you very much for the explanation, I understand it now :-)
