### ISSUE TITLE
Yuzu or Ryujinx in Windows10 with mesa

### ISSUE THREAD

**Issue by phasermaniac83** [pal1000/mesa-dist-win#70]
Hi!
I'm trying to get yuzu or Ryujinx (nintendo switch emulators) on a 10 years old pc with an amd hd6950.
I know my system is not powerful enough to run AA games, but I'm interested in 2d games like Ninja Warriors Once again.
I think my graphics card only supports opengl 4.4, and Yuzu needs 4.6, I think Ryujinx too.
Without mesa, both emulators crash on boot.
With mesa both emulator work setting:
@set MESA_GL_VERSION_OVERRIDE=4.6
@set MESA_GLSL_VERSION_OVERRIDE=460
@set GALLIUM_DRIVER=llvmpipe
but they run at 20fps.
I tried to run with:
@set GALLIUM_DRIVER=d3d12
@set LIBGL_ALWAYS_SOFTWARE=1
as I have read it is faster but both crashed. Why? maybe GLonD3D12 doesn't support newer Opengl versions?
I'm doing something wrong?
Thanks!

**Comment by pal1000** [comment]
> I tried to run with:
@set GALLIUM_DRIVER=d3d12
@set LIBGL_ALWAYS_SOFTWARE=1
as I have read it is faster but both crashed. Why? maybe GLonD3D12 doesn't support newer Opengl versions?

It only supports OpenGL 3.3.
Also 20FPS with llvmpipe in a Nintendo Switch game, honestly you can't ask for more.

**Comment by phasermaniac83** [comment]
Ok thanks!
