### ISSUE TITLE
Lavapipe not working with Zink driver in MSVC package (21.2.0-rc3)

### ISSUE THREAD

**Issue by fridenmf** [pal1000/mesa-dist-win#74]
I saw that you made a pre-release yesterday with Zink driver included in the MSVC package, and wanted to try out that together with Lavapipe, but I can't get it working.

I'm using he following environment variables:
GALLIUM_DRIVER=zink
ZINK_USE_LAVAPIPE=true

And with these DLLs from the mesa3d-21.2.0-rc3-release-msvc\x64 folder:
libglapi.dll
opengl32.dll

With this, wglCreateContextAttribsARB returns nullptr with attributes:
WGL_CONTEXT_MAJOR_VERSION_ARB, 4,
WGL_CONTEXT_MINOR_VERSION_ARB, 5,
WGL_CONTEXT_PROFILE_MASK_ARB, WGL_CONTEXT_CORE_PROFILE_BIT_ARB

I also tried setting the environment variable VK_ICD_FILENAMES=lvp_icd.x86_64.json together with the files lvp_icd.x86_64.json and vulkan_lvp.dll beside the executable and still the same behavior. 

As a last note, if I remove ZINK_USE_LAVAPIPE=true and VK_ICD_FILENAMES=lvp_icd.x86_64.json, then I can run Zink on top of my Nvidia driver and it seems to work well. I've also tried all the combinations of LIBGL_ALWAYS_SOFTWARE=true, MESA_GL_VERSION_OVERRIDE=4.5, and also tried to go the GLES route through libGLESv2.dll but I always get the same behavior of wglCreateContextAttribsARB returning a nullptr.

I can run Mesa with the GL, GLES and DirectX 12 software variants so that works fine, it's just Lavapipe that I can't get working. I don't know if I'm missing something or if Lavapipe is not supported yet since it's only a release candidate, but any help would be helpful. Thanks in advance and keep up the good work with the builds!

**Comment by pal1000** [comment]
You must always use absolute PATH without quotes with `VK_ICD_FILENAMES`, see [Vulkan ICD discovery docs](https://github.com/KhronosGroup/Vulkan-Loader/blob/master/loader/LoaderAndLayerInterface.md#icd-discovery).

**Comment by fridenmf** [comment]
Changing to an absolute path worked great, thanks for the quick reply!
