### ISSUE TITLE
Configuring NS emulators

### ISSUE THREAD

**Issue by I-i-I-iIi-I-i-I** [pal1000/mesa-dist-win#76]
How to properly configure mesa for Nintendo Switch emulators (yuzu, ryujinx)? And then my video adapter supports a maximum of OpenGL 3.3, and for emulators you need 4.6. I download mesa, open perappdeploy.cmd, specify the path of the folder with the emulator, enter the name of the emulator executable file, answer y to the 64-bit application and desktop drivers, answer everything else n. After that, I create a cmd file with the following content:
@set MESA_GL_VERSION_OVERRIDE=4.6COMPAT
@set MESA_GLSL_VERSION_OVERRIDE=460
@emulator_name.exe

But when you start the game in the emulator, both crash with an OpenGL error.
Yuzu writes in the logs:
Frontend <Error> yuzu\bootmanager.cpp:OpenGLSharedContext:143: Unable to create main openGL context
Frontend <Error> yuzu\bootmanager.cpp:OpenGLSharedContext:158: Unable to create shared openGL context
Frontend <Error> yuzu\bootmanager.cpp:OpenGLSharedContext:158: Unable to create shared openGL context

And Ryujinx writes this:
|E| Application : Unhandled exception caught: SPB.Platform.Exceptions.PlatformException: SetPixelFormat failed for dummy context: 1114
at SPB.Platform.WGL.WGLHelper.EnsureInit()
at SPB.Platform.WGL.WGLHelper.CreateContext(IntPtr& windowHandle, FramebufferFormat framebufferFormat, Int32 major, Int32 minor, OpenGLContextFlags flags, Boolean directRendering, IntPtr shareContext)
at SPB.Platform.WGL.WGLOpenGLContext.Initialize(NativeWindowBase window)
at Ryujinx.Ui.GlRenderer.IntializeOpenGL()
at Ryujinx.Ui.GlRenderer.OnDrawn(Context cr)
at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)

What am I doing wrong?

**Comment by pal1000** [comment]
Try without compatibility profile.
````
@set MESA_GL_VERSION_OVERRIDE=4.6
@set MESA_GLSL_VERSION_OVERRIDE=460
````

**Comment by I-i-I-iIi-I-i-I** [comment]
It doesn't work. The errors that the emulators show seem to indicate that OpenGL cannot be initialized, since this error does not occur without mesa, and my video card is detected in the logs, but both emulators crash due to the lack of OpenGL 4.6. And what is the strangest thing, opengl32.dll from some video from YouTube about the Citra fix, it works. That is, if you throw this particular file from the video into the folder with the emulator, and run it with the cmd parameters like mine, then Ryujinx is initialized and shows the video adapter in the logs as:
|N| GUI.RenderLoop Gpu PrintGpuInformation: VMware, Inc. llvmpipe (LLVM 8.0, 128 bits) (4.6 (Compatibility Profile) Mesa 20.1.8)
and even runs the game, but in a frame rate of less than one fps.

Yuzu no longer swears at OpenGL with this file, but after a few seconds after launch, it immediately closes, while there are no errors in the Yuzu log, although it seems that there are this in the log:
Failed to enumerate devices with error: VK_ERROR_INITIALIZATION_FAILED

From this situation, I only have one thing: everything works from the dll with the video to YouTube, namely, llvmpipe is initialized through cmd, and it is not even initialized through opengl32 or perappdeploy from github, no matter what driver I specify through @set GALLIUM_DRIVER.

Here is a link to an archive from a YouTube video that contains opengl32, which for some reason works for me: http://www.mediafire.com/file/u82omm1fy9oeg20/file

What should I do with all this?

**Comment by pal1000** [comment]
Since your GPU is capped at OpenGL 3.3, llvmpipe is the only option for OpenGL. You could try zink if your GPU is Vulkan capable, but then you would most likely have been able to run it with your GPU by default.  For Vulkan rendering you can use lavapipe or [swiftshader](https://github.com/pal1000/swiftshader-dist-win).
