### ISSUE TITLE
No fix-libvulkan-1.dll-missing-error.cmd in MinGW release package

### ISSUE THREAD

**Issue by SteelTitanium** [pal1000/mesa-dist-win#78]
Despite what the readme says, no such file seems to exist inside the package.

**Comment by pal1000** [comment]
You should read what readme says more carefully
````
This tool is only bundled in MinGW release package when needed because only releases for which zink driver was built with MSYS2 MinGW-W64 vulkan-devel package group are affected. The decision to use this Vulkan SDK over LunarG's is done based on which comes with newer loader and headers.
````
This basically states that it's only bundled when you can hit that error as it's known from build time already if it's going to occur or not.
