### ISSUE TITLE
add opencl support

### ISSUE THREAD

**Issue by congzhangzh** [pal1000/mesa-dist-win#81]
Hi,

The opencl in Mesa seems be a great state, is that possible to add support to it on windows, even just llvmpipe will be very helpful.

I have a step-by-step guide on how to build and test opencl on debian, hope this give basic help. https://github.com/congzhangzh/hello_cl

Tks,
Cong

**Comment by pal1000** [comment]
I still have a few things to sort out before I can build CLonD3D12 and clover. See #34.

**Comment by congzhangzh** [comment]
Ok, If verify is needed, I can give help:)

**Comment by donizettilorenzo** [comment]
POCL anyone?

**Comment by pal1000** [comment]
As of 21.3.6-2 both clover over llvmpipe and CLonD3D12 are available.

**Comment by congzhangzh** [comment]
Cool
