### ISSUE TITLE
Support for Dozen?

### ISSUE THREAD

**Issue by oscarbg** [pal1000/mesa-dist-win#93]
Hi,
Dozen has been merged to Mesa.. (https://www.phoronix.com/scan.php?page=news_item&px=Vulkan-On-Direct3D-12-Dzn-Merge)
it's a "Vulkan on D3D12" Mesa driver.. don't know how mature it is in initial state, don't know if good idea to include in initial 22.1rc1 release(?)..
just opening issue to keep track of dozen on mesa-dist-win..

thanks..

**Comment by pal1000** [comment]
I don't know if it's too early but building it was really easy so it will appear in 22.1rc1.
